### ISSUE TITLE
exception with emojis ? 

### ISSUE THREAD

**Issue by revolunet** [DISIC/jedonnemonavis.numerique.gouv.fr#53]
Looks like submitting comments with emojis breaks the submission 😱

<img width="1215" alt="Capture d’écran 2024-03-10 à 14 59 34" src="https://github.com/DISIC/jedonnemonavis.numerique.gouv.fr/assets/124937/1e159e74-d32d-454f-beaf-580a365d4a48">

<img width="347" alt="Capture d’écran 2024-03-10 à 15 00 19" src="https://github.com/DISIC/jedonnemonavis.numerique.gouv.fr/assets/124937/d9b88bf9-a2a7-4e33-96e9-7a174badfe03">

I hope there is some sentry of similar exception-catcher mechanism here to prevent lose of citizen submissions 😬

déso DossierFacile :)

**Comment by revolunet** [comment]
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOTJiYTFodnRocDM5aTFrcWlqYjFmNmZiMTB3ZWRlZWt4aXI5eDhmbyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/U7bo3ZBR8lcKSmGdlT/giphy.gif)

**Comment by revolunet** [comment]
@YoannNumericite

**Comment by ClementNumericite** [comment]
@revolunet wrong repo :) 

ici l'outil actuellement en ligne de xWiki : https://github.com/DISIC/observatoire

**Comment by revolunet** [comment]
Ok je remonte ça là-bas merciii !
